/** Real renderer checks for lightweight, status-aware mascot motion. */
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { mkdir } from 'node:fs/promises';
import { startQaProvider } from './qa-provider.mjs';
const require = createRequire(import.meta.url);
const { _electron } = require('playwright');
const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
await mkdir(resolve('artifacts/qa'), { recursive: true });
const provider = await startQaProvider({ chunkDelayMs: 15 });
const app = await _electron.launch({ executablePath: process.env.DOTS_SMOKE_EXECUTABLE || require('electron'), args: process.env.DOTS_SMOKE_EXECUTABLE ? ['--demo-mode'] : [resolve('.'), '--demo-mode'], env });
const checks = [], errors = [];
const check = (name, result = true) => { assert.ok(result, name); checks.push(name); console.log(`PASS ${name}`); };
try {
  const page = await app.firstWindow(); page.on('pageerror', error => errors.push(error.message));
  await page.waitForSelector('.overview-dot-card');
  await app.evaluate(({BrowserWindow}) => { const win = BrowserWindow.getAllWindows()[0]; win.setSize(1100,760); win.focus(); });
  await page.mouse.move(1,1);
  await page.waitForFunction(()=>document.querySelector('.overview-dot-card .dot-mascot')?.dataset.motionVisible==='true');
  check('Visible dots breathe and blink',await page.locator('.overview-dot-card .dot-mascot').first().evaluate(element=>getComputedStyle(element.querySelector('.dot-mascot-motion')).animationName==='mascot-idle' && getComputedStyle(element.querySelector('.dot-mascot-eyes')).animationName==='mascot-blink'));
  await page.locator('.overview-dot-card').first().hover();
  check('Hover greeting is finite',await page.locator('.overview-dot-card .dot-mascot-motion').first().evaluate(element=>getComputedStyle(element).animationName==='mascot-hello' && getComputedStyle(element).animationIterationCount==='1'));
  await page.mouse.move(1,1);
  check('Scrolling pauses mascot motion',await page.evaluate(()=>{document.querySelector('.overview-page').dispatchEvent(new Event('scroll'));return document.documentElement.classList.contains('mascots-scrolling') && getComputedStyle(document.querySelector('.overview-dot-card .dot-mascot-motion')).animationPlayState==='paused';}));
  await page.waitForFunction(()=>!document.documentElement.classList.contains('mascots-scrolling'));
  await page.locator('.overview-page').evaluate(element=>element.scrollTop=element.scrollHeight);
  await page.waitForFunction(()=>document.querySelector('.overview-dot-card .dot-mascot')?.dataset.motionVisible==='false');
  check('Offscreen avatars pause',await page.locator('.overview-dot-card .dot-mascot-motion').first().evaluate(element=>getComputedStyle(element).animationPlayState==='paused'));
  await page.locator('.overview-page').evaluate(element=>element.scrollTop=0);
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  check('Unfocused window pauses all mascot loops',await page.evaluate(()=>document.documentElement.classList.contains('mascots-hidden')));
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].focus());
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await page.waitForFunction(()=>!document.documentElement.classList.contains('mascots-hidden'));
  const dot = await page.evaluate(async baseUrl=>{
    const profile = await window.dots.api.saveProviderProfile({label:'Motion QA',baseUrl,defaultModel:'qa-model',apiKey:'fixture'});
    return window.dots.api.createDot({name:'Motion QA',description:'Animation check',instructions:'',color:'#78b7a0',emoji:'🌱',providerId:profile.id,model:'qa-model',notify:false,permissions:{files:'none',shell:false,web:false,outsideWorkspace:false,approval:'never'}});
  },provider.baseUrl);
  await page.locator('.sidebar-dot').filter({hasText:'Motion QA'}).click();
  await page.waitForSelector('.profile-mascot .dot-mascot');
  const run = await page.evaluate(id=>window.dots.api.startRun(id,'[qa:slow] Think carefully.',{newSession:true}),dot.id);
  await page.waitForFunction(()=>document.querySelector('.profile-mascot .dot-mascot')?.dataset.mood==='working');
  check('Working status uses its own motion and sparkle',await page.locator('.profile-mascot .dot-mascot').evaluate(element=>getComputedStyle(element.querySelector('.dot-mascot-motion')).animationName==='mascot-working' && getComputedStyle(element.querySelector('.mascot-sparkle')).animationName==='mascot-sparkle'));
  await page.screenshot({path:resolve('artifacts/qa/cute-working-dot.png')});
  await page.waitForFunction(async id=>(await window.dots.api.listRuns(id))[0]?.status==='succeeded',dot.id);
  await page.waitForFunction(()=>document.querySelector('.profile-mascot .dot-mascot')?.dataset.mood==='idle');
  check('Finished work returns to idle motion');
  await page.evaluate(id=>window.dots.api.updateDot(id,{permissions:{files:'write',shell:false,web:false,outsideWorkspace:false,approval:'ask'}}),dot.id);
  await page.evaluate(id=>window.dots.api.startRun(id,'Create a file to check approvals.',{newSession:true}),dot.id);
  await page.waitForFunction(()=>document.querySelector('.profile-mascot .dot-mascot')?.dataset.mood==='curious');
  check('Approval requests use a curious tilt',await page.locator('.profile-mascot .dot-mascot-motion').evaluate(element=>getComputedStyle(element).animationName==='mascot-curious'));
  await page.evaluate(async()=>{for(const approval of await window.dots.api.listApprovals())await window.dots.api.resolveApproval(approval.id,true);});
  await page.waitForFunction(async id=>(await window.dots.api.listRuns(id)).every(run=>run.status==='succeeded'),dot.id);
  await page.evaluate(id=>window.dots.api.setDotPaused(id,true),dot.id);
  await page.waitForFunction(()=>document.querySelector('.profile-mascot .dot-mascot')?.dataset.mood==='resting');
  check('Paused dots rest with no loop',await page.locator('.profile-mascot .dot-mascot-motion').evaluate(element=>getComputedStyle(element).animationName==='none'));
  await page.evaluate(id=>window.dots.api.setDotPaused(id,false),dot.id);
  await page.emulateMedia({reducedMotion:'reduce'});
  check('Reduced motion disables body, eyes and sparkles',await page.locator('.profile-mascot .dot-mascot').evaluate(element=>['.dot-mascot-motion','.dot-mascot-eyes','.mascot-sparkle'].every(selector=>getComputedStyle(element.querySelector(selector)).animationName==='none')));
  check('No renderer errors',errors.length===0);
  console.log(JSON.stringify({passed:checks.length,errors,runId:run.id}));
} finally { await app.close(); await provider.close(); }
